server:
  port: 9898

spring:
  application:
    name: exams


  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/*******
    username: username
    password: password





user:
  errors:
    exception-messages:
      UserAlreadyExists:
        code: 1001
        statusCode: 400
        msg:
          AR: المستخدم موجود مسبقا"
          EN: User Already Exist

      NoSuchUser:
        code: 1000
        statusCode: 404
        msg:
          AR: لا يوجد مستخدم مسجل
          EN: No Such user registred